### ISSUE TITLE
does not work on servers

### ISSUE THREAD

**Issue by Spilya** [KrLite/Ive-Spoken#2]
Hi, the mod does not work on servers, I do not know what it is related to, but I assume that it is related to the signature of the message. Everything works on the vanilla server, but not on purpur

**Comment by Spilya** [comment]
And yes, I am installing this mod on the client, there is not a single plugin installed on the server

**Comment by KrLite** [comment]
How does it behave? I'm not familiar with purpur (which I have only heard of a few times) so I need more detailed information to deal with.
It works fine on vanilla servers because I have tested it in real environments and all the workarounds are vanilla-like. I may not test it on purpur in future releases due to the maintenance pressure. So if it appears to be a purpur-only issue, it may be given a lower priority and won't be fixed.
Thanks for reporting this issue anyway!

**Comment by KrLite** [comment]
I'm labeling this issue `wontfix`. If there's any update, please let me know.
